/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Experience(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/pepeWorldFinal.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.keys(actions).forEach((key) => {
      actions[key].play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="c57b1394e0a04c9387073f712fe8a11afbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group name="Plane" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <mesh
          name="bnkme_base001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_base001.geometry}
          material={materials.Shader_material}
          position={[-101.578, -3.443, -35.955]}
          scale={[28.197, 14.364, 35.008]}
        />
        <mesh
          name="bnkme_bank_foundation"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bank_foundation.geometry}
          material={materials.Shader_material}
          position={[-101.675, -14.278, -47.584]}
          scale={6.247}
        />
        <mesh
          name="bnkme_roof"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_roof.geometry}
          material={materials.Shader_material}
          position={[-101.578, 59.792, -32.199]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-43.981, -1.503, -48.952]}
        />
        <mesh
          name="bnkme_base"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_base.geometry}
          material={materials.Shader_material}
          position={[-101.578, -13.492, 15.822]}
          scale={[143.39, 128.316, 128.316]}
        />
        <mesh
          name="bnkme_door"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_door.geometry}
          material={materials.Shader_material}
          position={[-102.984, 19.613, 3.041]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[14.143, 3.128, 14.143]}
        />
        <mesh
          name="bnkme_pepe"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_pepe.geometry}
          material={materials.Shader_material}
          position={[-102.135, 102.949, -6.299]}
          scale={8.762}
        />
        <mesh
          name="bnkme_gold_bars"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_bars.geometry}
          material={materials.Shader_material}
          position={[-179.8, -13.492, -50.56]}
          scale={6.247}
        />
        <mesh
          name="bnkme_gold_coin001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_coin001.geometry}
          material={materials.Shader_material}
          position={[-87.908, -13.499, -16.914]}
          scale={6.247}
        />
        <mesh
          name="bnkme_trees"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_trees.geometry}
          material={materials.Shader_material}
          position={[-17.749, 5.866, -67.214]}
          rotation={[0, 0.934, 0]}
          scale={4.3}
        />
        <mesh
          name="bnkme_columns"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_columns.geometry}
          material={materials.Shader_material}
          position={[-101.675, -14.278, -47.584]}
          scale={6.247}
        />
        <mesh
          name="bnkme_decals"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_decals.geometry}
          material={materials.Shader_material}
          position={[-102.223, 25.847, -58.345]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[1.892, 5.353, 2.817]}
        />
        <mesh
          name="bnkme_inscription"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_inscription.geometry}
          material={materials.Shader_material}
          position={[-101.675, -14.278, -47.584]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bushes"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bushes.geometry}
          material={materials.Shader_material}
          position={[19.138, -7.643, 89.331]}
          scale={6.247}
        />
        <mesh
          name="bnkme_arc_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_arc_002.geometry}
          material={materials.Shader_material}
          position={[-98.374, 24.084, 122.82]}
          rotation={[0, 0.115, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_gold_monument_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_monument_002.geometry}
          material={materials.Shader_material}
          position={[-102.431, 19.423, 72.306]}
          rotation={[0.429, 0.738, 1.272]}
          scale={[2.029, 2.762, 2.029]}
        />
        <mesh
          name="bnkme_chest_base_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_chest_base_002.geometry}
          material={materials.Shader_material}
          position={[-34.855, -6.773, 48.286]}
          rotation={[0, -0.513, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_chest_lid_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_chest_lid_002.geometry}
          material={materials.Shader_material}
          position={[-34.862, 5.19, 45.748]}
          rotation={[0, -0.513, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_gold_bars_pile_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_bars_pile_002.geometry}
          material={materials.Shader_material}
          position={[-35.439, 1.327, 49.346]}
          rotation={[0.021, -0.569, -0.068]}
          scale={6.247}
        />
        <mesh
          name="bnkme_chest_base_003"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_chest_base_003.geometry}
          material={materials.Shader_material}
          position={[-160.621, -6.773, 48.286]}
          rotation={[0, 0.529, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_chest_lid_003"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_chest_lid_003.geometry}
          material={materials.Shader_material}
          position={[-160.629, 5.19, 45.748]}
          rotation={[0, 0.529, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_gold_bars_pile_003"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_bars_pile_003.geometry}
          material={materials.Shader_material}
          position={[-161.206, 1.327, 49.346]}
          rotation={[0.02, 0.473, -0.088]}
          scale={6.247}
        />
        <mesh
          name="bnkme_road"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_road.geometry}
          material={materials.Shader_material}
          position={[-100.876, -13.255, 78.631]}
          rotation={[0, 1.254, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_arc_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_arc_001.geometry}
          material={materials.Shader_material}
          position={[121.498, 6.257, 178.661]}
          rotation={[0, 0.115, 0]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_001.geometry}
          material={materials.Shader_material}
          position={[119.291, -27.777, 53.839]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_002.geometry}
          material={materials.Shader_material}
          position={[119.611, -25.725, 71.994]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_003"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_003.geometry}
          material={materials.Shader_material}
          position={[101.295, -24.148, 100.391]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_004"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_004.geometry}
          material={materials.Shader_material}
          position={[101.295, -24.12, 132.533]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_005"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_005.geometry}
          material={materials.Shader_material}
          position={[101.295, -24.423, 153.11]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_006"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_006.geometry}
          material={materials.Shader_material}
          position={[119.611, -24.148, 100.391]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_007"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_007.geometry}
          material={materials.Shader_material}
          position={[119.611, -24.12, 132.533]}
          scale={6.247}
        />
        <mesh
          name="bnkme_bush_008"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_bush_008.geometry}
          material={materials.Shader_material}
          position={[119.611, -24.423, 153.11]}
          scale={6.247}
        />
        <mesh
          name="bnkme_chest_base_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_chest_base_001.geometry}
          material={materials.Shader_material}
          position={[119.618, -28.127, -121.637]}
          scale={6.247}
        />
        <mesh
          name="bnkme_chest_lid_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_chest_lid_001.geometry}
          material={materials.Shader_material}
          position={[119.611, -16.164, -124.175]}
          scale={6.247}
        />
        <mesh
          name="bnkme_column"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_column.geometry}
          material={materials.Shader_material}
          position={[119.611, -1.183, -97.305]}
          scale={[4.515, 29.555, 4.515]}
        />
        <mesh
          name="bnkme_decal_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_decal_001.geometry}
          material={materials.Shader_material}
          position={[119.611, 58.238, -40.147]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[5.353, 5.353, 2.817]}
        />
        <mesh
          name="bnkme_decal_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_decal_002.geometry}
          material={materials.Shader_material}
          position={[119.611, 68.602, -40.147]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.892, 5.353, 2.817]}
        />
        <mesh
          name="bnkme_gold_bar_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_bar_001.geometry}
          material={materials.Shader_material}
          position={[119.611, -32.713, 13.318]}
          scale={6.247}
        />
        <mesh
          name="bnkme_gold_bars_pile_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_bars_pile_001.geometry}
          material={materials.Shader_material}
          position={[119.033, -20.028, -120.577]}
          rotation={[0.018, -0.056, -0.078]}
          scale={6.247}
        />
        <mesh
          name="bnkme_gold_coin_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_coin_001.geometry}
          material={materials.Shader_material}
          position={[119.611, -27.096, 28.863]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[6.247, 1.251, 6.247]}
        />
        <mesh
          name="bnkme_gold_monument_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_gold_monument_001.geometry}
          material={materials.Shader_material}
          position={[118.855, -3.03, -153.099]}
          rotation={[0.429, 0.738, 1.272]}
          scale={[2.029, 2.762, 2.029]}
        />
        <mesh
          name="bnkme_road_brick_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_road_brick_001.geometry}
          material={nodes.bnkme_road_brick_001.material}
          position={[119.611, 56.648, -40.147]}
          scale={6.247}
        />
        <mesh
          name="bnkme_road_brick_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_road_brick_002.geometry}
          material={nodes.bnkme_road_brick_002.material}
          position={[163.046, 56.648, -40.147]}
          scale={6.247}
        />
        <mesh
          name="bnkme_road_brick_003"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_road_brick_003.geometry}
          material={nodes.bnkme_road_brick_003.material}
          position={[142.908, 56.648, -40.147]}
          scale={6.247}
        />
        <mesh
          name="bnkme_road_brick_004"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_road_brick_004.geometry}
          material={nodes.bnkme_road_brick_004.material}
          position={[100.184, 56.648, -40.147]}
          scale={6.247}
        />
        <mesh
          name="bnkme_tree_001"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_tree_001.geometry}
          material={materials.Shader_material}
          position={[120.233, -15.459, 2.235]}
          scale={7.032}
        />
        <mesh
          name="bnkme_tree_002"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_tree_002.geometry}
          material={materials.Shader_material}
          position={[119.611, -32.782, -24.849]}
          scale={2.101}
        />
        <mesh
          name="bnkme_tree_003"
          castShadow
          receiveShadow
          geometry={nodes.bnkme_tree_003.geometry}
          material={materials.Shader_material}
          position={[119.611, -5.728, -70.685]}
          scale={6.247}
        />
        <group
          name="Armature"
          position={[-99.796, -2.223, 12.777]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <skinnedMesh
            name="Plane__0001"
            geometry={nodes.Plane__0001.geometry}
            material={materials["Scene_-_Root.001"]}
            skeleton={nodes.Plane__0001.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pepeWorldFinal.glb");
